package com.arkentos.util.mapping;
// Generated Mar 26, 2018 11:02:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name="HRCANDIDATE"
)
public class Hrcandidate  implements java.io.Serializable {


     private String nic;
     private Status status;
     private String fullname;
     private String position;
     private String mobile;
     private String email;
     private Date interviewdate;
     private String address;
     private String remarks;

    public Hrcandidate() {
    }

	
    public Hrcandidate(String nic) {
        this.nic = nic;
    }

     
   
     @Id 

    
    @Column(name="NIC", unique=true, nullable=false, length=15)
     public String getNic() {
        return nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }
     

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    

    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name="ADDRESS", length=50)
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    
    

    
    @Column(name="FULLNAME", length=50)
     public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="POSITION", length=10)
    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="MOBILE", length=15) 
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INTERVIEWDATE", length=23)
     public Date getInterviewdate() {
        return interviewdate;
    }

    public void setInterviewdate(Date interviewdate) {
        this.interviewdate = interviewdate;
    }
    
     @Column(name="REMARKS", length=50)    
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }



}


