package com.arkentos.util.mapping;
// Generated Feb 16, 2018 9:38:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.naming.NamingException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import sun.net.www.protocol.mailto.MailToURLConnection;

/**
 * Systemaudit generated by hbm2java
 */
@Entity
@Table(name="HRINTERVIEW"
)
public class Hrinterview  implements java.io.Serializable {
    

    
     private String nic;
     private Date interviewdate;
     private Systemuser interviewedby;
     private Status interviewstatus; 
     private Systemuser approvedby;
     private String remarks;
     private Status status;

    public Hrinterview() {
    }

    public Hrinterview(String nic, Date interviewdate, Systemuser interviewedby, Status interviewstatus, Systemuser approvedby, String remarks, Status status) {
       
        this.nic = nic;
        this.interviewdate = interviewdate;
        this.interviewedby = interviewedby;
        this.interviewstatus = interviewstatus;
        this.approvedby = approvedby;
        this.remarks = remarks;
        this.status = status;
    }
   
    @Id 

    @Column(name="NIC", unique=true, nullable=false, length=15) 
     public String getNic() {
        return nic;
    } 
     
    public void setNic(String nic) {
        this.nic = nic;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
     @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INTERVIEWEDBY")
    public Systemuser getInterviewedby() {
        return interviewedby;
    }

    public void setInterviewedby(Systemuser interviewedby) {
        this.interviewedby = interviewedby;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPROVEDBY") 
    public Systemuser getApprovedby() {
        return approvedby;
    }

    public void setApprovedby(Systemuser approvedby) {
        this.approvedby = approvedby;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INTERVIEWDATE", length=23)
     public Date getInterviewdate() {
        return interviewdate;
    }

    public void setInterviewdate(Date interviewdate) {
        this.interviewdate = interviewdate;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INTERVIEWSTATUS")
    public Status getInterviewstatus() {
        return interviewstatus;
    }

    public void setInterviewstatus(Status interviewstatus) {
        this.interviewstatus = interviewstatus;
    }

    @Column(name="REMARKS", length=64)    
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
     



}


