package com.arkentos.util.mapping;
// Generated Mar 26, 2018 11:02:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name="PAGE"
)
public class Page  implements java.io.Serializable {


     private String pagecode;
     private Status status;
     private String description;
     private String url;
     private Byte sortkey;
     private Set<Pagetask> pagetasks = new HashSet<Pagetask>(0);
     private Set<Sectionpage> sectionpages = new HashSet<Sectionpage>(0);

    public Page() {
    }

	
    public Page(String pagecode) {
        this.pagecode = pagecode;
    }
    public Page(String pagecode, Status status, String description, String url, Byte sortkey, Set<Pagetask> pagetasks, Set<Sectionpage> sectionpages) {
       this.pagecode = pagecode;
       this.status = status;
       this.description = description;
       this.url = url;
       this.sortkey = sortkey;
       this.pagetasks = pagetasks;
       this.sectionpages = sectionpages;
    }
   
     @Id 

    
    @Column(name="PAGECODE", unique=true, nullable=false, length=4)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="URL", length=128)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="SORTKEY", precision=2, scale=0)
    public Byte getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Byte sortkey) {
        this.sortkey = sortkey;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pagetask> getPagetasks() {
        return this.pagetasks;
    }
    
    public void setPagetasks(Set<Pagetask> pagetasks) {
        this.pagetasks = pagetasks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Sectionpage> getSectionpages() {
        return this.sectionpages;
    }
    
    public void setSectionpages(Set<Sectionpage> sectionpages) {
        this.sectionpages = sectionpages;
    }




}


