package com.arkentos.util.mapping;
// Generated Feb 16, 2018 9:38:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResponseCodes generated by hbm2java
 */
@Entity
@Table(name="RESPONSE_CODES"
)
public class ResponseCodes  implements java.io.Serializable {


     private String responsecode;
     private String description;

    public ResponseCodes() {
    }

	
    public ResponseCodes(String responsecode) {
        this.responsecode = responsecode;
    }
    public ResponseCodes(String responsecode, String description ) {
       this.responsecode = responsecode;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="RESPONCECODE", unique=true, nullable=false, length=10)
    public String getResponsecode() {
        return this.responsecode;
    }
    
    public void setResponsecode(String responsecode) {
        this.responsecode = responsecode;
    }

    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    




}


