package com.arkentos.util.mapping;
// Generated Mar 26, 2018 11:02:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name="SECTION")
public class Section  implements java.io.Serializable {


     private String sectioncode;
     private Status status;
     private String description;
     private Byte sortkey;
     private Set<Userrolesection> userrolesections = new HashSet<Userrolesection>(0);
     private Set<Sectionpage> sectionpages = new HashSet<Sectionpage>(0);

    public Section() {
    }

	
    public Section(String sectioncode) {
        this.sectioncode = sectioncode;
    }
    public Section(String sectioncode, Status status, String description, Byte sortkey, Set<Userrolesection> userrolesections, Set<Sectionpage> sectionpages) {
       this.sectioncode = sectioncode;
       this.status = status;
       this.description = description;
       this.sortkey = sortkey;
       this.userrolesections = userrolesections;
       this.sectionpages = sectionpages;
    }
   
     @Id 

    
    @Column(name="SECTIONCODE", unique=true, nullable=false, length=4)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SORTKEY", precision=2, scale=0)
    public Byte getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Byte sortkey) {
        this.sortkey = sortkey;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="section")
    public Set<Userrolesection> getUserrolesections() {
        return this.userrolesections;
    }
    
    public void setUserrolesections(Set<Userrolesection> userrolesections) {
        this.userrolesections = userrolesections;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="section")
    public Set<Sectionpage> getSectionpages() {
        return this.sectionpages;
    }
    
    public void setSectionpages(Set<Sectionpage> sectionpages) {
        this.sectionpages = sectionpages;
    }




}


